### ISSUE TITLE
Date in widget

### ISSUE THREAD

**Issue by etrahretep** [stoneC0der/ubersicht-clock#1]
Per request. Could you add the date to the widget?
Copy/paste code is sufficient

Thanks

**Comment by stoneC0der** [comment]
Hi, I added the date but cannot test the code as I currently don't have access to a MacBook.

Initially it should work and display the date in the 02/17/2022 format after you set **showDate** to ***true***,
if you would like it formatted differently set the **useAltenateCommand** to ***true*** and choose one of the format in the **dateFormat** object as in the [README.md](https://github.com/stoneC0der/ubersicht-clock/blob/dev/README.md).

I push the changes to a [dev](https://github.com/stoneC0der/ubersicht-clock/tree/dev) branch if you'll be so kind to test and report back so I can update the widget I'll really appreciate it thanks.

**Comment by etrahretep** [comment]
Initial start won't show anything. I'll try later when looking at the code.

**Comment by stoneC0der** [comment]
did you change the value of the constant below:
Line 87
```jsx
/**
 * Enable date in widget
 */
export const showDate = false; // true or false
````
if not, you need to manually change it to ***true*** since it's optional.

**Comment by etrahretep** [comment]
I changed  showDate and useAlternateCommand to true; no show.
const date = useAlternateCommand ? setDateFormat(datetime[1], dataFormat.a) : datetime[1];
is used twice. If I comment the first one I get:

<img width="1344" alt="Schermafbeelding 2022-02-17 om 19 43 21" src="https://user-images.githubusercontent.com/42773309/154550178-952763b5-33c2-4840-939e-a766f5e40a76.png">

The dimmed is the version without date... 
Can't figure it out.

**Comment by stoneC0der** [comment]
Yes I did changed the code a bit but the HTML will still be displayed I'll fix soon, that screenshot was of great help

**Comment by etrahretep** [comment]
Awesome. Looking forward!
Could you do something with DatetoLocaleString? (Dutch)

btw, removing  {(Date) ? ` from {(Date) ? `<h2 className="date"> {date} </h2>` : ``} shows me this:

<img width="789" alt="Schermafbeelding 2022-02-17 om 21 26 28" src="https://user-images.githubusercontent.com/42773309/154565065-b4fb99c3-3109-4d62-9ba9-a3ef6b19df76.png">

Still missing day number and order is wrong...

**Comment by stoneC0der** [comment]
I think everything should work as expected now

**Comment by etrahretep** [comment]
Cedric, you are a hero! Thanks for this brilliant solution.

**Comment by stoneC0der** [comment]
thanks for your assistance too, I'll update the widget then.
